name: Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: snok/install-poetry@v1.2.1

    - name: Install dependencies
      run: sudo apt update && sudo apt install -y --no-install-recommends python3-venv

    - name: Make poetry use Python 3
      run: sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 10

    - name: Build package
      run: poetry build

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@bea5cda687c2b79989126d589ef4411bedce0195
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
